PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX Orphanet_: <http://www.orpha.net/ORDO/Orphanet_#>
PREFIX ORDO: <http://www.orpha.net/ORDO/>

select ?label ?predicat ?predlabel ?o WHERE {
?s ?predicat ?o.
    optional {?predicat rdfs:label ?predlabel}.
    optional {?s rdfs:label ?label}.
optional {?o ?m ?v.
?v rdfs:label ?e}.
filter (?s = ORDO:Orphanet_558)
}
ORDER BY ?o
